<div class='LBBBanner'>
<div class='LBBBannerRight'>
<a href="homepage.php" class="header">Home</a>
<a href="userlogin.php" class="header">Log in</a>
<a href="register.php" class="header">Register</a>
<a href="help.php" class="header">Help</a>
</div>
<div class='LBBBannerText'>
<nobr><a class="header" href="http://www.larrybeth.com" target="blank">LarryBeth</a> style!</nobr>
</div>
</div>

